# Generated by Django 3.0.7 on 2020-06-19 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_personalaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryBundle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('code', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('code', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=11)),
                ('entry_bundle_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_entry.EntryBundle')),
                ('main_account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.MainAccount')),
                ('personal_account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.PersonalAccount')),
                ('secondary_account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.SecondaryAccount')),
            ],
        ),
    ]
