# Generated by Django 3.0.7 on 2020-07-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0005_entry_entry_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='entry_type',
            field=models.CharField(choices=[('Dr', 'dr'), ('Cr', 'cr')], max_length=2),
        ),
    ]
