# Generated by Django 3.0.7 on 2020-07-19 09:40

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0006_auto_20200702_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='symbol_number',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entrybundle',
            name='detail',
            field=models.TextField(default='nothing', max_length=1536),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=11, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='entry',
            name='entry_type',
            field=models.CharField(choices=[('dr', 'Dr'), ('cr', 'Cr')], max_length=2),
        ),
    ]
