# Generated by Django 3.0.7 on 2020-07-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0007_auto_20200719_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
    ]
