# Generated by Django 3.0.7 on 2020-07-19 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0008_auto_20200719_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrybundle',
            name='detail',
        ),
    ]
