# Generated by Django 3.0.7 on 2020-07-01 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_personalaccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainaccount',
            name='code',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='personalaccount',
            name='code',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='secondaryaccount',
            name='code',
            field=models.FloatField(),
        ),
    ]
